### ISSUE TITLE
SignalWhenComplete<TResult> Completes invocation without setting the result

### ISSUE THREAD

**Issue by AlexpKun** [JSkimming/Castle.Core.AsyncInterceptor#15]
When using AsyncTimingInterceptor I noticed that the return value in my IInvocation object is the task that is created by InterceptAsynchronous instead of the returned value of the function.
What I think happens is that SignalWhenComplete calls CompletedInvocation before the 
invocation.ReturnValue = SignalWhenComplete<TResult>(invocation, state);
line is executed, leaving the returned value an unstarted task.
I fixed it locally by setting 
invocation.ReturnValue = result;
just before calling CompletedInvocation in SignalWhenComplete.

**Comment by JSkimming** [comment]
Hi @AlexpKun, thanks for your interest in this project.

Can you describe what is the problem is, with example code?

You say:

> I noticed that the return value in my IInvocation object is the task that is created by InterceptAsynchronous instead of the returned value of the function

That is the expected behaviour, it has to _replace_ the original task, to ensure the calling code awaits the interception code.

In the past I had a naive implementation of the interceptor, that didn't use async/await, but purely added a `ContinueWith()` to a `Task` if it was returned. I found was it worked 99% of the time, but occasionally timings would be lost or out of sequence. This was because the calling code didn't await the timing code, so it didn't always happen in the correct sequence, or at all.

**Comment by AlexpKun** [comment]
Thanks for the prompt reply.

Let me try to explain myself better:
SignalWhenComplete<TResult> will invoke CompletedInvocation before
returning the result. Meaning that if you access the return value in a
CompletedInvocation override, you will get a Task instance, instead of the
preferable actual return value of the async method.
Perhaps my usage is wrong, but I expected the CompletedInvocation to be
invoked once the task itself was run to completion, not just its
invocation. You already wait for the original invocation result in it, so
when invoking CompletedInvocation you already know that the task completed,
might as well pass on the result.

Here is my SignalWhenComplete implementation:

private async Task<TResult> SignalWhenComplete<TResult>(IInvocation
invocation, TState state)
        {
            // Get the task to await.
            var returnValue = (Task<TResult>)invocation.ReturnValue;

            TResult result = await returnValue.ConfigureAwait(false);

            invocation.ReturnValue = result;

            // Signal that the invocation has been completed.
            CompletedInvocation(invocation, state);

            return result;
        }

I am also using AsyncTimingInterceptor and this allows me to access the
return value in the CompletedTiming callback.

I tried the continue with method as well, but then luckily found your
extension :)

Thanks.

**Comment by JSkimming** [comment]
Hi @AlexpKun 

I see what you are trying to do, and I caution against doing so.

The return value of  invocation **must** be a `Task<TResult>` and you are setting it to be a `TResult` if this were to propagate to the calling code I suspect the outcome would be catastrophic with some strange runtime errors.

I've applied your change and ran the tests, they all pass, but only because the calling code is probably executing before your change overwrites the return value.

I assume you want to implement a solution that can access the underlying return value (not `Task<TResult>` but `TResult`) of a method that returns.

I think this is a good idea, and I have an idea that may help. Let me push some code quickly.

**Comment by JSkimming** [comment]
@AlexpKun here's a potential update to [ProcessingAsyncInterceptor](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/blob/6622f3026fb561eacb7294402ccaa0f3b9bd029f/src/Castle.Core.AsyncInterceptor/ProcessingAsyncInterceptor.cs), would that work for you?

**Comment by AlexpKun** [comment]
Yeah, that works great. Thanks!

**Comment by JSkimming** [comment]
@AlexpKun I've just release a [new version](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/releases/tag/v1.3.0) and pushed to [NuGet](https://www.nuget.org/packages/Castle.Core.AsyncInterceptor/1.3.0).

If this library is useful to you, would you mind [up-voting my answer in stack overflow](https://stackoverflow.com/a/43272955). Hopefully it'll drive more to this repo.
