### ISSUE TITLE
.net core Task.Run(() => task).GetAwaiter().GetResult() is out of date

### ISSUE THREAD

**Issue by gokhanabatay** [JSkimming/Castle.Core.AsyncInterceptor#165]
Hi,
Is it necessary task wrapping for .net core  with `Task.Run(() => task).GetAwaiter().GetResult()`, just call task.GetAwaiter().GetResult() below several dotnet samples ?

AsyncInterceptor causes too much Task "thread starvation" when we write a method that calls other method, example: method 1 -> Task -> inner method 2 -> Task -> inner method 3 -> Task

![image](https://user-images.githubusercontent.com/9988911/190396529-f4ce24c2-fe20-403a-9019-7e8b6a2030d2.png)

Under high load we see thread starvation, suspension, locking(init new thread) causes performance impact.

https://stackoverflow.com/questions/17284517/is-task-result-the-same-as-getawaiter-getresult/17284612#17284612 is out of date by writer?

https://stackoverflow.com/questions/17284517/is-task-result-the-same-as-getawaiter-getresult/38530225#38530225 is accepted by same writer above link.

` GetAwaiter().GetResult() prevents a thrown exception being wrapped in a AggregateException.`  
RethrowIfFaulted already checks if its aggreagete exception or not?

https://github.com/dotnet/aspnetcore/commit/6965a66f18a6229a1f7bee76b4b2c499f44b1ca1

https://github.com/dotnet/aspnetcore/commit/360b80efddbe4c1e39bf34be120dc7b45b289e4c

https://github.com/dotnet/aspnetcore/commit/96c1668c54c83c8c91dd54e182870f13c511f77a

https://github.com/dotnet/runtime/commit/d7a062e5cd297e255c80764017e09cc51196dfa6

```c#
 private static void InterceptSynchronousVoid(AsyncInterceptorBase me, IInvocation invocation)
    {
        Task task = me.InterceptAsync(invocation, invocation.CaptureProceedInfo(), ProceedSynchronous);

        // If the intercept task has yet to complete, wait for it.
        if (!task.IsCompleted)
        {
            // Need to use Task.Run() to prevent deadlock in .NET Framework ASP.NET requests.
            // GetAwaiter().GetResult() prevents a thrown exception being wrapped in a AggregateException.
            // See https://stackoverflow.com/a/17284612
            Task.Run(() => task).GetAwaiter().GetResult();
        }

        task.RethrowIfFaulted();
    }
```

**Comment by gokhanabatay** [comment]
For simplification we just implement 'IAsyncInterceptor' described OPTION 2 thank you for good documentation.

**Comment by JSkimming** [comment]
@gokhanabatay, thanks for the feedback.

It's become apparent that `AsyncInterceptorBase` is flawed, and I plan to deprecate it. Transitioning from async to non-async code is fraught, and the use of `Task.Run()` is an attempt to mitigate the challenges, but it is still not successful.

On the branch [benchmark](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/tree/benchmark/test/Castle.Core.AsyncInterceptor.Benc,hmark) I'm experimenting with some micro-benchmarks, and I need to disable the tests with `AsyncInterceptorBase` otherwise it locks up. Maybe it's the thread starvation you've highlighted, but IIRC, I tried removing the `Task.Run()` without success hence why I decided to deprecate it.

When I find the time (famous last words), I plan to work on a few new features. I think support for `ValueTask` would be useful,  as well as improved documentation, though thank you for the kind words regarding the current documentation. When I tackle that, I'll push a release with `AsyncInterceptorBase` deprecated.

**Comment by JSkimming** [comment]
@gokhanabatay after your feedback, I've swapped options 1 & 2 in the readme and added a warning to the [new option 2](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/tree/0720bae8277263eb60e2c58c22477082933453b6#option-2-extend-asyncinterceptorbase-class-to-intercept-invocations "Option 2 - previously Option 1") (previously Option 1).

Hopefully, this will warn people to be cautious with `AsyncInterceptorBase`.

**Comment by gokhanabatay** [comment]
Thank you @JSkimming
